### ISSUE TITLE
is ember-shiki/src/modifiers/shiki-render.ts public API?

### ISSUE THREAD

**Issue by NullVoxPopuli** [IgnaceMaes/ember-shiki#15]
I have a use case where I need to highlight prose but don't exactly need to use all the features of `<CodeBlock>`

thanks!

**Comment by IgnaceMaes** [comment]
Is it possible to achieve what you want via the `CodeBlock` component and style it using [the CSS variables](https://github.com/IgnaceMaes/ember-shiki/blob/main/ember-shiki/src/styles.css#L2-L12)? That's how it's currently intended to be used.

The modifier itself is not indented to be used, in the way that it's not documented and the API isn't also super ergonomic as you need to pass in the callbacks. And I'm not sure if it's worth keeping semver for this interface.

But as it's still pre 1.0 I'm open to feedback based on real world use and see what could be changed or improved. What is the use case?

**Comment by NullVoxPopuli** [comment]
Well, the only way to use CodeBlock on prose documents is with remark or showdown plugins to swap out code fences vith CodeBlock.

I just added support for adding remark plugins in ember-repl, so this is the approach i'm going with on limber, tutorial, ember-primitives, etc

This is basically what i have planned: https://github.com/NullVoxPopuli/limber/pull/1306/files#diff-da94a790ce9da1a545b6521c515aa789c9b6e6f44306020089e78acf12112649R80

It's the same strategy that the learning team would need to use as well to update the ember docs, if they wanted to do that.
Cc @mansona @minthamio @locks

It's not a huge deal, fwiw, these sorts of markdown processing plugins are super tiny.
The gap i'm filling is really one from highlight.js and prism, where you can tell them to highlight a whole container element, and it'll find the pre/code blocks and highlight them (provided the language tags / aliases are correct)

So maybe the approach with shiki is just .. all around safer? More deliberate? That's fine be me!
