### ISSUE TITLE
gjs language tags in markdown are not highlighted

### ISSUE THREAD

**Issue by NullVoxPopuli** [IgnaceMaes/ember-shiki#18]
My config:
```js
    'ember-shiki': {
      defaultLanguages: ['gjs', 'gts', 'css', 'bash', 'js', 'ts', 'markdown'],
      defaultThemes: ['one-dark-pro'],
    },
```

<details><summary>My Markdown</summary>

~~~md
# Limber Editor

## With JavaScript

code fence tags can be used to directly render components,
as well as render the code snippet the live code comes from.

Options:

- `live` - _renders in place_
- `live preview` _renders in place, placing the source after the live render_
- `live preview below` _renders in place, placing the live render below the source_

```gjs live
<template>
  Hello, Glimmer!
</template>
```

```gjs live preview
import Component from '@glimmer/component';
import { tracked } from '@glimmer/tracking';
import { on } from '@ember/modifier';

export default class HelloWorld extends Component {
  @tracked count = 0;

  increment = () => this.count += 1;

  <template>
    <p>You have clicked the button {{this.count}} times.</p>

    <button {{on "click" this.increment}}>Click</button>
  </template>
}
```

~~~

</details>

![image](https://github.com/IgnaceMaes/ember-shiki/assets/199018/ad8985b9-16a5-48da-9d46-91aa32630349)

**Comment by IgnaceMaes** [comment]
This is expected default behaviour as Shiki's built-in Markdown grammar doesn't include `gjs`/`gts`. I looked into adding this support in https://github.com/chiragpat/vscode-glimmer/pull/9 for `vscode-glimmer`.

To get it working with `ember-shiki` you could register a custom version of [the Markdown grammar](https://github.com/shikijs/shiki/blob/main/packages/shiki/languages/markdown.tmLanguage.json) with the embedded code fence grammar detection.

In the other issue you also asked how to not load every embedded language by default. Adapting the custom grammar there could also be a solution, although not the prettiest.

I started documenting loading custom grammars in https://github.com/IgnaceMaes/ember-shiki/pull/16 for reference.

**Comment by IgnaceMaes** [comment]
Going to close this issue as it's either solved by loading custom grammars, or adding support upstream in https://github.com/shikijs/textmate-grammars-themes.
