### ISSUE TITLE
Shikiji?

### ISSUE THREAD

**Issue by NullVoxPopuli** [IgnaceMaes/ember-shiki#24]
Is there a way to choose between Shiki and Shikij?

**Comment by IgnaceMaes** [comment]
Not easily.

I doubt it's worth building in logic to do this, as it makes things complicated. This should probably just be forked and made into `ember-shikiji`.

Shikiji's goal is to eventually merge back into shiki AFAIK, but in the meantime that still leaves them out of sync.

**Comment by IgnaceMaes** [comment]
Looks like this won't be necessary _soon_ 🙂 

https://github.com/shikijs/shiki/pull/557

**Comment by IgnaceMaes** [comment]
Closing in favour of https://github.com/IgnaceMaes/ember-shiki/issues/25
